const images = {
	menu: require('../images/menu.png'),
	back: require('../images/back.png'),
	search: require('../images/search.png'),
	view:  require('../images/view.png'),
	word: require('../images/word.png'),
    sort: require('../images/sort.png'),
    repository: require('../images/repository.png'),
	folder: require('../images/folder.png'),
	upload: require('../images/Upload.png'),
	download: require('../images/download.png'),
	pdf: require('../images/pdf.png'),
	spreedsheet: require('../images/spreedsheet.png'),
	ppt: require('../images/ppt.png'),
	jpg: require('../images/jpg.png'),
	tif: require('../images/tif.png'),
	xls: require('../images/xls.png'),
	doc: require('../images/doc.png'),
	wmv: require('../images/wmv.png'),
	delete: require('../images/delete_07.png'),
	move: require('../images/move_07.png'),
	media: require('../images/media_11.png'),
	edit: require('../images/rename.png'),
	splash: require('../images/splash.jpg'),
	right: require('../images/right.png'),
	popuplock: require('../images/popuplock.png'),
	cancel: require('../images/cancel.png'),
	popupuser: require('../images/popupuser.png'),
	popupfolder: require('../images/popupfolder.png'),
	placeholder: require('../images/placeholder.png'),
	first: require('../images/first.png'),
	second: require('../images/second.png'),
	third: require('../images/third.png'),
	mp3: require('../images/mp3.png'),
	play: require('../images/play.png'),
	pause: require('../images/pause.jpg'),
	stop: require('../images/stop.png'),
	//logo: require('../images/logo.png'),
	logo: require('../images/PRISMLOGO.png'),
	logo2: require('../images/BombayHeader.png'),
	logo3: require('../images/logo.png'),
	logoLight: require('../images/logo-light.png'),
	Backround: require('../images/backroundImage.jpg'),
	Backround2: require('../images/backgroundImage2.jpg')


}

export default images